name: Akamai API for GitHub Actions

on:
  push:
    paths:
    - '**.py'

env:
    # リクエストのターゲットブランチ
    GET_REF: ${{ github.ref }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install edgegrid-python
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    # git diffをするためにターゲットブランチをフェッチする
    - name: 'Fetch'
      run: |
        echo "TARGET_BRANCH=`echo ${GET_REF} | awk -F / 'END{print $NF}'`" >> $GITHUB_ENV
        git fetch --depth 1 origin ${TARGET_BRANCH}

    - name: 'python run'
      run: |
        # ターゲットブランチとHEAD間で、追加,変更されたpythonファイルのパスを取得してループ処理
        for file in $(git diff origin/${TARGET_BRANCH} HEAD --diff-filter=AM --name-only -- "*.py") ; do
          # ここで任意の処理
          python ${file}
        done
